### ISSUE TITLE
Skeleton/Tailwind Project

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/bexis2-data-curation-ui#1]
This is going to be the starting point of the whole project (at least from the source code point of view)

## Tasks

- [x] creation of project (with proper versions of skeleton and tailwind)
- [x] introduction into svelte (https://svelte.dev)
- [x] introduction into skeleton (https://www.skeleton.dev/)
- [x] introduction into tailwind (https://tailwindcss.com/)
- [x] usage of existing GitHub project for versioning control of files (https://github.com/BEXIS2/bexis2-data-curation-ui, pull/push, related to #2)
- [x] integration of @bexis2/bexis2-core-ui package
- [x] usage/testing of existing input components from @bexis2/bexis2-core-ui
- [x] build/debug of project

## Questions

- [x] How do I create a new Skeleton/Tailwind project and what are the different options at the creation process?
- [x] How do I import external libraries and use them?
- [x] How do I build and run that application?
- [x] How do I change configurations?

**Comment by sventhiel** [comment]
Als Einstieg in die Programmierung im Projekt wird ein Skeleton/Tailwind-Projekt benötigt. Anschließend müssen weitere Aspekte betrachtet und eingehalten werden.

**Comment by TitoPrausee** [comment]
![Image](https://github.com/BEXIS2/bexis2-data-curation-ui/assets/145434937/b553d5d9-e132-44b5-bea6-232f7d1b621e)

**Comment by geofranzi** [comment]
https://www.npmjs.com/package/@bexis2/bexis2-core-ui
