### ISSUE TITLE
UML, Class Diagram

### ISSUE THREAD

**Issue by sventhiel** [BEXIS2/bexis2-data-curation-ui#3]
Within the project and the related new entities, it is necessary to document the properties and relationships between each other and also potential links to existing BEXIS2 entities.

## Tasks

- [x] creation of class diagram within the shared Miro board (or another open source tool and reference inside Miro board)
- [x] documentation of classes within Miro board (for better understanding and reasoning of decisions)

## Questions

- [x] What is a class diagram and why do I need one?

# notes
- [x] add xpath to entry
- [x] abstract note type, user id, usertype (data curator | user) 
- [x] add datetime to note & entry
- [x] entry has only one note list
- [x] add booleans to note , (user has changed, data curator has approved)

**Comment by TitoPrausee** [comment]
![Image](https://github.com/BEXIS2/bexis2-data-curation-ui/assets/145434937/985eaf12-860f-4aca-a80e-ff443ca1d714)
