### ISSUE TITLE
Identification of UI Components

### ISSUE THREAD

**Issue by sventhiel** [BEXIS2/bexis2-data-curation-ui#4]
The user interface of the BEXIS2 data curation "tool" needs proper UI components. Therefore, a research of existing Skeleton components is necessary and important. This task is highly related and depending on the conceptual design the tool.

## Tasks

- [x] look-up and comparison of potential Skeleton UI components
- [x] identification of external UI components (in case Skeleton does not offer proper ones)

## Questions

- [x] Which UI components do I need?
- [x] What are the differences between similar solutions and how to choose one?

**Comment by TitoPrausee** [comment]
Clarify requirements: Understand the requirements for the website.

Research: Search for the web elements you need.

Selection: Select suitable elements.

Integration: Integrate the selected elements into the web page.

Testing: Check that the integrated elements work as expected.

Documentation: Note down the elements used and their functions.
