### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by sventhiel** [BEXIS2/bexis2-data-curation-ui#5]
Most of the data  that is transferred between backend and frontend within BEXIS2 are formatted as JSON. This task is related to and depending on #3, because based on the chosen classes and properties, the JSON files might differ as well. So, because of proper APIs within the backend do not exist yet, the creation and usage of JSON files (that look like the "future" API responses) is a good intermediate solution.

## Tasks

- [x] creation of JSON sample(s) to represent the "commenting" incl. direct reactions

## Questions

- [x] What is JSON and how does it look like?
- [x] What are attributes within JSON and do I need them (or should I use them)?
- [x] Are there some edge cases which cannot be represented within JSON?
- [x] Do I have enough example data/files to map/identify different/all scenarios?

**Comment by TitoPrausee** [comment]
![Image](https://github.com/BEXIS2/bexis2-data-curation-ui/assets/145434937/6d690028-6c1a-471c-a927-1a6d836ddbdb)
