### ISSUE TITLE
Model(s)

### ISSUE THREAD

**Issue by sventhiel** [BEXIS2/bexis2-data-curation-ui#6]
Due to the usage of [typescript](https://www.typescriptlang.org/), the usage of classes/interfaces within the project #1 is emphasized.

## Tasks

- [ ] creation of necessary model(s)
- [ ] identification of proper data types for the properties

## Questions

- [ ] What are the benefits of using models instead of "simple" objects?
