### ISSUE TITLE
SCRUM

### ISSUE THREAD

**Issue by sventhiel** [BEXIS2/bexis2-data-curation-ui#8]
Within our group, we follow the pattern called "SCRUM". 

## Tasks

- [x] introduction into [SCRUM](https://www.youtube.com/watch?v=bec3yG7xJhU&list=PLDzW0odStMVKqAtaBug6RkLHPlhHzKd9z)

## Questions

- [x] What is SCRUM?
- [x] Which roles do exist, and what are the corresponding task(s) for each of them?
